"""add_voice_to_episode

Revision ID: bca359048d1c
Revises: de7313ad594e
Create Date: 2026-07-09 23:20:04.516894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bca359048d1c'
down_revision: Union[str, Sequence[str], None] = 'de7313ad594e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_article_url'), 'article', type_='unique')
    op.create_index(op.f('ix_article_url'), 'article', ['url'], unique=False)
    op.add_column('episode', sa.Column('voice', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='af_heart'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'voice')
    op.drop_index(op.f('ix_article_url'), table_name='article')
    op.create_unique_constraint(op.f('uq_article_url'), 'article', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
