"""add_cohost_fields

Revision ID: bd7aa9a582c1
Revises: a4817a03beef
Create Date: 2026-07-12 15:13:57.092487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd7aa9a582c1'
down_revision: Union[str, Sequence[str], None] = 'a4817a03beef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('episode', sa.Column('voice_cohost', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='af_sky'))
    op.add_column('episode', sa.Column('podcast_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='monologue'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'podcast_format')
    op.drop_column('episode', 'voice_cohost')
    # ### end Alembic commands ###
