"""add_summary_script_to_podcastjob

Revision ID: fe51cebf59c0
Revises: 6a13e6033196
Create Date: 2026-06-15 22:14:04.228112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe51cebf59c0'
down_revision: Union[str, Sequence[str], None] = '6a13e6033196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcastjob', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('podcastjob', sa.Column('podcast_script', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcastjob', 'podcast_script')
    op.drop_column('podcastjob', 'summary')
    # ### end Alembic commands ###
